name: ClusterRDP Smart (Production Edition)

on:
  workflow_dispatch:

jobs:
  cluster-rdp-smart:
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites on Runner
        run: |
          sudo apt update -qq
          sudo apt update -qq
          sudo apt install -y jq python3 python3-pip curl ca-certificates gnupg lsb-release
          # إضافة مفتاح Docker الرسمي
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          # إضافة مستودع Docker
          echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
              | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
         sudo apt update -qq
         # تثبيت Docker و containerd
         sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


      - name: Install and start Tailscale on Runner
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled --state=/tmp/tailscaled.state &
          sleep 5
          sudo tailscale up --authkey="${{ secrets.TAILSCALE_AUTH_KEY }}" --hostname="runner" --accept-dns=false

      - name: Build RDP Docker Image
        run: |
          docker build -t rdp-ubuntu:latest -f Dockerfile.rdp .

      - name: Ensure script permissions
        run: chmod +x scripts/*.sh

      - name: Launch Production Smart Cluster
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        run: |
          echo "⏱ Starting VM creation sequence (Production timings)..."
          ./scripts/create_rdp_vm_smart.sh 1 &
          sleep 7200
          ./scripts/create_rdp_vm_smart.sh 2 &
          sleep 7200
          ./scripts/create_rdp_vm_smart.sh 3 &
          echo "✅ All VMs launched in production sequence."

      - name: Monitor Cluster (long-running)
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        run: ./scripts/monitor_cluster_smart.sh
